# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Node'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install @angular/cli -g'

- task: Npm@1
  inputs:
    command: 'install'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Enterprise Subscription(710645ab-94a8-4e2b-af20-35c0af057678)'
    appType: 'webApp'
    WebAppName: 'AzAngularApp'
    packageForLinux: 'dist/ngweb-api-core/'
